;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Action.Dodge",DevComment="")
+GameplayTagList=(Tag="Ability.Action.PrimaryAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Weapon.Slot1",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Weapon.Slot2",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Weapon.Slot3",DevComment="")
+GameplayTagList=(Tag="Ability.Enemy.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Ability.Enemy.Attack.Ranged",DevComment="")
+GameplayTagList=(Tag="Data.Item.BountyXP",DevComment="")
+GameplayTagList=(Tag="Data.Item.HealAmount",DevComment="")
+GameplayTagList=(Tag="Data.MonsterLevel",DevComment="")
+GameplayTagList=(Tag="Data.Projectile.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.Passive.Damage",DevComment="모든 무기 공통 패시브 기본 데미지")
+GameplayTagList=(Tag="Data.Weapon.Passive.AttackDelay",DevComment="모든 무기 공통 패시브 공격 주기 딜레이")
+GameplayTagList=(Tag="Data.Weapon.Passive.AttackRange",DevComment="모든 무기 공통 패시브 기본 사거리 범위")
+GameplayTagList=(Tag="Data.Weapon.Selected.Damage",DevComment="주무기 공통 조작 선택 사격 기본 데미지")
+GameplayTagList=(Tag="Data.Weapon.Selected.AttackDelay",DevComment="주무기 공통 조작 선택 사격 공격 주기 딜레이")
+GameplayTagList=(Tag="Data.Weapon.Common.AttackSpeed",DevComment="모든 무기 공통 글로벌 공격 속도 배율")
+GameplayTagList=(Tag="Data.Weapon.Selected.PenetrationCount",DevComment="[플라즈마 라이플] 선택 사격 몬스터 관통 수치")
+GameplayTagList=(Tag="Data.Weapon.Common.ProjectileRange",DevComment="[라이플/샷건] 사출되는 투사체의 최종 소멸 사거리")
+GameplayTagList=(Tag="Data.Weapon.Selected.PullRadius",DevComment="[그래비티 해머] 선택 사격 좀비 흡착 블랙홀 반경 범위")
+GameplayTagList=(Tag="Data.Weapon.Common.KnockbackForce",DevComment="[그래비티 해머] 좀비를 타격하여 지도 끝으로 밀쳐내는 물리적 힘")
+GameplayTagList=(Tag="Data.Weapon.Passive.PullRadius",DevComment="[그래비티 해머] 패시브 땅 쿵 가격 시 좀비를 끌어당기는 미세 반경")
+GameplayTagList=(Tag="Data.Weapon.Selected.PelletCount",DevComment="[스프레드 샷건] 선택 사격 부채꼴로 사출되는 산탄 파편 총합 수")
+GameplayTagList=(Tag="Data.Weapon.Common.SpreadAngle",DevComment="[스프레드 샷건] 탄환이 흩뿌려지는 부채꼴 종횡 광각 폭 각도")
+GameplayTagList=(Tag="Data.Weapon.Passive.PelletCount",DevComment="[스프레드 샷건] 패시브 자동 사격 시 사출되는 기본 산탄 파편 수")
+GameplayTagList=(Tag="Data.Weapon.Passive.OrbitRadius",DevComment="[디펜스 드론] 캐릭터 배꼽 중심 드론이 회전 공전하는 순정 반경 크기")
+GameplayTagList=(Tag="Data.Weapon.Passive.DeflectProjectileDelay",DevComment="[디펜스 드론] 날아오는 원거리 좀비 독침 투사체를 지워내는 가드 감시 주기")
+GameplayTagList=(Tag="Data.Weapon.Passive.DeflectEnemyDelay",DevComment="[디펜스 드론] 근접해 몸뚱이에 비비려는 적을 팅겨내는 가드 감시 주기")
+GameplayTagList=(Tag="Data.Weapon.Passive.PushForce",DevComment="[디펜스 드론] 드론 배리어에 닿은 좀비를 밀쳐내는 물리적 넉백 저항 힘")
+GameplayTagList=(Tag="Data.Weapon.Passive.ExplosionRadius",DevComment="[마그넷 지뢰] 밟았을 때 쾅 터져나가는 자석 전기장 대폭발 반경 크기")
+GameplayTagList=(Tag="Data.Weapon.Passive.ExplosionDelay",DevComment="[마그넷 지뢰] 바닥 매설 완료 후 격발 격동 상태까지 걸리는 신관 선지연 시간")
+GameplayTagList=(Tag="Data.Weapon.Passive.SlowAmount",DevComment="[마그넷 지뢰] 잔류 파편 전기장을 밟은 좀비의 이동속도 고유 감속률 배율")
+GameplayTagList=(Tag="Data.Weapon.Passive.SlowTimer",DevComment="[마그넷 지뢰] 감속 디버프가 좀비 몸뚱이에 낙인되어 유지되는 지속 시간")
+GameplayTagList=(Tag="Data.Weapon.Passive.SlowAreaRadius",DevComment="[오라 모듈] 내 몸뚱이 상시 가동 방사능 전기 필드 장판의 총체적 영역 크기")
+GameplayTagList=(Tag="Data.Weapon.Passive.SlowAreaDelay",DevComment="[오라 모듈] 필드 내부 적들에게 틱 데미지 및 감속을 갱신 연산하는 주기 딜레이")
+GameplayTagList=(Tag="Data.Weapon.Passive.SlowAreaTimer",DevComment="[오라 모듈] 오라 장판 필드가 한 번 발동되었을 때 인게임에 켜져 있는 유지 타이머")
+GameplayTagList=(Tag="Data.Weapon.Passive.SlowAreaAmount",DevComment="[오라 모듈] 오라 장판 밟은 적 전용 이속 차감 슬로우 감속률 명찰")
+GameplayTagList=(Tag="ObjectPool.Enemy.Melee",DevComment="")
+GameplayTagList=(Tag="ObjectPool.Enemy.Ranged",DevComment="")
+GameplayTagList=(Tag="ObjectPool.Item.Gem",DevComment="")
+GameplayTagList=(Tag="ObjectPool.Item.Potion",DevComment="")
+GameplayTagList=(Tag="State.Combat.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Player.Ability.LockMovement",DevComment="")
+GameplayTagList=(Tag="State.Player.Ability.LockRotation",DevComment="")
+GameplayTagList=(Tag="State.Player.MagnetActive",DevComment="")
+GameplayTagList=(Tag="State.Player.Status.Invincible",DevComment="")
+GameplayTagList=(Tag="State.Weapon.Primary.GravityHammer.Passive",DevComment="")
+GameplayTagList=(Tag="State.Weapon.Primary.GravityHammer.Selected",DevComment="")
+GameplayTagList=(Tag="State.Weapon.Primary.PlasmaRifle.Passive",DevComment="")
+GameplayTagList=(Tag="State.Weapon.Primary.PlasmaRifle.Selected",DevComment="")
+GameplayTagList=(Tag="State.Weapon.Primary.SpreadShotgun.Passive",DevComment="")
+GameplayTagList=(Tag="State.Weapon.Primary.SpreadShotgun.Selected",DevComment="")
+GameplayTagList=(Tag="State.Weapon.Secondary.AuraModule.Passive",DevComment="")
+GameplayTagList=(Tag="State.Weapon.Secondary.DefenseDrone.Passive",DevComment="")
+GameplayTagList=(Tag="State.Weapon.Secondary.MagnetMine.Passive",DevComment="")

