;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Action.Dodge",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.AuraModule.AuraRadius",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.AuraModule.TickDamage",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.AuraModule.TickInterval",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.DefenseDrone.DeflectCooldown",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.DefenseDrone.OrbitRadius",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.DefenseDrone.PushForce",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.GravityHammer.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.GravityHammer.KnockbackForce",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.GravityHammer.PullRadius",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.GravityHammer.SlamCooldown",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.MagnetMine.DropInterval",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.MagnetMine.ExplosionDamage",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.MagnetMine.ExplosionRadius",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.MagnetMine.SlowAmount",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.PlasmaRifle.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.PlasmaRifle.PassiveRange",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.PlasmaRifle.PenetrationCount",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.PlasmaRifle.TickInterval",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.SpreadShotgun.DamagePerPellet",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.SpreadShotgun.FireCooldown",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.SpreadShotgun.PelletCount",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.SpreadShotgun.SpreadAngle",DevComment="")
+GameplayTagList=(Tag="State.Player.Ability.LockMovement",DevComment="")
+GameplayTagList=(Tag="State.Player.Ability.LockRotation",DevComment="")
+GameplayTagList=(Tag="State.Player.Status.Invincible",DevComment="")

